name: udp_server
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-190.0.dev

# Add regular dependencies here.
dependencies:
  protocol:
    path: ../protocol

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
